//
// Created by qiguo on 1/12/18.
//

#ifndef __TINYRPC_ERRLIST_H_
#define __TINYRPC_ERRLIST_H_

enum ERROR_CODE
{
    ERR_BASE_CODE = 100,
    ERR_INVALID_POINTER,
    ERR_INVALID_MESSAGE,
    ERR_INVALID_TYPE,
    ERR_FULL_POOL,
    ERR_INVALID_CONF
};

#endif //TINYRPC_ERRLIST_H
